name: Build PDFs

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst
        run: |
          sudo snap install typst 
      - name: Build PDFs
        run: |
          chmod +x scripts/*.sh
          scripts/build_pdfs.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: build/*.pdf

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdfs
          path: build
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.pdf
